name: Upload Image

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Path to the image file'
        required: true
        default: 'C:/Users/screen/Pictures/1.png'

jobs:
  upload-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Upload image to repository
        run: |
          # สร้าง directory สำหรับเก็บไฟล์
          mkdir -p ./images
          
          # คัดลอกไฟล์จากเครื่อง (ที่ระบุใน path)
          cp ${{ github.event.inputs.image }} ./images/
          
          # Commit และ push ไฟล์ที่เพิ่มไปยัง GitHub repository
          git config --global user.name "YourName"
          git config --global user.email "youremail@example.com"
          git add ./images/*
          git commit -m "Add image"
          git push origin main
