name: Upload Image Automatically

on:
  workflow_dispatch:   # ใช้คำสั่งจาก API หรือผู้ใช้
    inputs:
      file:
        description: 'Upload Image'
        required: true
        default: 'image.png'

jobs:
  upload-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload image to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: image
        path: ./path_to_your_image/image.png  # ต้องเปลี่ยน path ตามที่ไฟล์อยู่

    - name: Commit changes
      run: |
        git config --global user.email "youremail@example.com"   # ใส่อีเมล์
        git config --global user.name "Your Name"                 # ใส่ชื่อของคุณ
        git add .   
        git commit -m "Update image"
        git push
