name: Upload Images

on:
  repository_dispatch:
    types: [upload-images]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Decode and Save Image 1
        run: |
          echo "${{ github.event.client_payload.image1 }}" | base64 --decode > images/1.png

      - name: Decode and Save Image 2
        run: |
          echo "${{ github.event.client_payload.image2 }}" | base64 --decode > images/2.png

      - name: Decode and Save Image 3
        run: |
          echo "${{ github.event.client_payload.image3 }}" | base64 --decode > images/3.png

      - name: Save Upload Date
        run: |
          date '+%Y-%m-%d %H:%M:%S' > images/upload_date.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add images/*.png images/upload_date.txt
          git commit -m "Update images and upload date"
          git push
